version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - '.env.db'
  web:
    image: marswang92/react_on_rails_devise
    command: bash -c "bundle exec rake assets:precompile && bundle exec rails s -e production -p 3000 -b '0.0.0.0'"
    volumes:
      - ./public:/app/public
      - ./log:/app/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - '.env.web'
  nginx:
    image: nginx
    volumes_from:
      - web
    depends_on:
      - web
    volumes:
      - ./nginx.devel.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
